### ISSUE TITLE
Inputs (params) with the same name as outputs conflict each other

### ISSUE THREAD

**Issue by cjhkim** [guideline-tech/subroutine#15]
Since both params and outputs write methods onto the op instance, there's a potential for conflict when setting a param name equal to an output name.

Seems like this would be impossible to fix and be backwards compatible, so it seems like in the meantime, the op should at least raise in these cases.

Thoughts?

**Comment by mnelson** [comment]
Looking to handle that here: https://github.com/guideline-tech/subroutine/pull/19
