### ISSUE TITLE
Breaking changes?

### ISSUE THREAD

**Issue by aaronjensen** [guideline-tech/subroutine#23]
Hi,

We've been using subroutine (thanks!) for a bit now and just attempted to upgrade to 1.0 from 0.9. It seems that there are breaking changes, but I cannot find where they are documented. Could you please point me to that documentation or give a sense of what we should do to migrate?

Thanks!

**Comment by amlivingamliving** [comment]
Plus one on this issue – we like the library very much, but the change without documentation concerns us. Could you please point us in the right direction vis-a-vis a migration strategy? Much appreciated!

**Comment by mnelson** [comment]
Apologies for the trouble here, I'll work on a changelog. It was a comprehensive refactor, but the major changes are with how fields are managed -- `Op._fields` is now `Op.field_configurations` and are `Subroutine::Fields::Configuration` objects. There's another change where accessing params expands association to native fields by default to provide a consistent response, regardless of the inputs provided to the op. For example:

```ruby
class SomeOp
  association :user
  association :resource, polymorphic: true
end

user = User.find(4)
op = SomeOp.new(user: user, resource: user)
op.params #=> { user_id: 4, resource_type: "User", resource_id: 4 }
op.params_with_association #=> { user: <User:103204 @id=4>, resource: <User:103204 @id=4> }
```

@aaronjensen @amlivingamliving Do you have specific traces that you could share so I can be sure to include the migration strategy for those use cases?

**Comment by mnelson** [comment]
Here's a start: https://github.com/guideline-tech/subroutine/blob/master/CHANGELOG.MD

**Comment by mnelson** [comment]
Feel free to throw any followup questions in here and I can provide specific migration strategies.
