### ISSUE TITLE
Default value for field can be modified by changing the field value on instance

### ISSUE THREAD

**Issue by pboling** [guideline-tech/subroutine#3]
Will write a failing spec, and submit a PR that fixes it.

Some data types need to be `deep_dup`'d when used as default values.

**Comment by pboling** [comment]
Fixed by https://github.com/guideline-tech/subroutine/pull/4

**Comment by pboling** [comment]
@mnelson did you see this?

**Comment by mnelson** [comment]
I missed this. Thanks for pinging me again.

**Comment by mnelson** [comment]
0.5.1 is now live with your changes. https://rubygems.org/gems/subroutine/versions/0.5.1

Thanks again
